### ISSUE TITLE
Constructors for speech events

### ISSUE THREAD

**Issue by saschanaz** [w3c/speech-api#14]
Currently `new SpeechSynthesisEvent("pending", { utterance: new SpeechSynthesisUtterance() })` works on Edge and Firefox but throws on Chrome.

Edge: only requires the first argument
Firefox: requires both the first and second arguments
Chrome: always throws

Can we spec this to align browser behaviors?

**Comment by foolip** [comment]
When sending https://github.com/w3c/speech-api/pull/45 I didn't read the issue description to spot that Edge and Firefox already disagree about whether the argument should be required.

In this case, I would like to align with Firefox, because otherwise the `utterance` attribute has to be nullable, and the only reason for it would be this constructor. That makes it less clear from looking at the IDL whether it can be null for user-agent-created events.

**Comment by minorninth** [comment]
Interop is good, but what's the use case for constructing one of these?

I suppose it's potentially useful for writing unit tests, but I can't think of anything else.

**Comment by smaug----** [comment]
Testing, and consistency with other events.
